In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectKBest, chi2, RFE

import pickle
import time

In [2]:
# Creating Function(s) :

def SelectKBest_Classification(indep_X,dep_Y,n):
        test = SelectKBest(score_func=chi2, k=n)
        print(f"Selecting top {n} features using Chi-Square test")
        
        fit1= test.fit(indep_X,dep_Y)
        selectk_features = fit1.transform(indep_X)
        return selectk_features

def train_test_split_and_StandardScaler(indep_X,dep_Y):
        X_train, X_test, Y_train, Y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, Y_train, Y_test

def Confusion_Matrix(classifier,X_test):
    y_pred = classifier.predict(X_test)

    from sklearn.metrics import confusion_matrix
    confusion_matrix = confusion_matrix(Y_test, y_pred)

    from sklearn.metrics import classification_report 
    classification_report=classification_report(Y_test, y_pred)

    from sklearn.metrics import accuracy_score
    accuracy_score=accuracy_score(Y_test, y_pred)         

    return classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score 

def LogisticRegression(X_train,Y_train,X_test):       
    # Fitting K-NN to the Training set
    from sklearn.linear_model import LogisticRegression
    classifier = LogisticRegression(random_state = 0) 
    classifier.fit(X_train, Y_train)

    # Calling a Created Function - Confusion_Matrix(classifier,X_test) which returns - classifier, X_test, Y_test, ConfusionMatrix, report, accuracy_score
    classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score = Confusion_Matrix(classifier,X_test)
    return classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score   

def SVM_Linear(X_train,Y_train,X_test):

    from sklearn.svm import SVC
    classifier = SVC(kernel = 'linear', random_state = 0)
    classifier.fit(X_train, Y_train)

    # Calling a Created Function - Confusion_Matrix(classifier,X_test) which returns - classifier, X_test, Y_test, ConfusionMatrix, report, accuracy_score
    classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score = Confusion_Matrix(classifier,X_test)
    return classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score

def SVM_Non_Linear(X_train,Y_train,X_test):

    from sklearn.svm import SVC
    classifier = SVC(kernel = 'rbf', random_state = 0)
    classifier.fit(X_train, Y_train)

    # Calling a Created Function - Confusion_Matrix(classifier,X_test) which returns - classifier, X_test, Y_test, ConfusionMatrix, report, accuracy_score
    classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score = Confusion_Matrix(classifier,X_test)
    return classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score

def Naive_Bayes(X_train,Y_train,X_test):       

    from sklearn.naive_bayes import GaussianNB
    classifier = GaussianNB()
    classifier.fit(X_train, Y_train)

    # Calling a Created Function - Confusion_Matrix(classifier,X_test) which returns - classifier, X_test, Y_test, ConfusionMatrix, report, accuracy_score
    classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score = Confusion_Matrix(classifier,X_test)
    return classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score

def KNN(X_train,Y_train,X_test):

    from sklearn.neighbors import KNeighborsClassifier
    classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
    classifier.fit(X_train, Y_train)

    # Calling a Created Function - Confusion_Matrix(classifier,X_test) which returns - classifier, X_test, Y_test, ConfusionMatrix, report, accuracy_score
    classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score = Confusion_Matrix(classifier,X_test)
    return classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score

def DecisionTree(X_train,Y_train,X_test):

    # Fitting K-NN to the Training set
    from sklearn.tree import DecisionTreeClassifier
    classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    classifier.fit(X_train, Y_train)

    # Calling a Created Function - Confusion_Matrix(classifier,X_test) which returns - classifier, X_test, Y_test, ConfusionMatrix, report, accuracy_score
    classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score = Confusion_Matrix(classifier,X_test)
    return classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score

def RandomForest(X_train,Y_train,X_test):

    from sklearn.ensemble import RandomForestClassifier
    classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
    classifier.fit(X_train, Y_train)

    # Calling a Created Function - Confusion_Matrix(classifier,X_test) which returns - classifier, X_test, Y_test, ConfusionMatrix, report, accuracy_score
    classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score = Confusion_Matrix(classifier,X_test)
    return classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score


def SelectK_Classification(accuracy_LogisticRegression, accuracy_SVM_Linear, accuracy_SVM_NonLinear, 
                           accuracy_KNN, accuracy_NaiveBayes, accuracy_DecisionTree, accuracy_RandomForest): 

    dataframe=pd.DataFrame(index=['ChiSquare'],columns=['Logistic Regression','SVM Linear','SVM Non Linear','KNN',
                                                        'Naive Bayes','Decision Tree','Random Forest'])
    
    #Function - enumerate() acts as a Counter which Iterates index starting from 0 (by default) and their item(s) from the iterable
    #Use enumerate() when We need both Position in the loop (number) and its value from the iterable (idex)
    
    for indexCount,indexValue in enumerate(dataframe.index):      
        dataframe['Logistic Regression'][indexValue]=accuracy_LogisticRegression[indexCount]       
        dataframe['SVM Linear'][indexValue]=accuracy_SVM_Linear[indexCount]
        dataframe['SVM Non Linear'][indexValue]=accuracy_SVM_NonLinear[indexCount]
        dataframe['KNN'][indexValue]=accuracy_KNN[indexCount]
        dataframe['Naive Bayes'][indexValue]=accuracy_NaiveBayes[indexCount]
        dataframe['Decision Tree'][indexValue]=accuracy_DecisionTree[indexCount]
        dataframe['Random Forest'][indexValue]=accuracy_RandomForest[indexCount]
    return dataframe

In [3]:
#1.Loading Original Dataset : 
dataset=pd.read_csv("Pre-processed_CKD_Data.csv",index_col=None)
print(dataset.shape)
dataset.head()

(399, 25)

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.0,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.0,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.0,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.0,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.0,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes

In [4]:
#2.Duplicating the Original Dataset
dataset2 = dataset

#3.Classifying the Nominal Columns in Dataset : 
dataset2 = pd.get_dummies(dataset2, drop_first=True)
print(dataset2.shape)
dataset2.head()

(399, 28)

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.0,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.0,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.0,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.0,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.0,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1

In [5]:
#4.Assigning Variables (Independent/Dependent) : 

indep_X = dataset2.drop('classification_yes', 1)
print(indep_X.shape)

dep_Y = dataset2['classification_yes']
print(dep_Y.shape)

(399, 27)
(399,)

In [24]:
#5.Calling a Created Function - select_K_Best(indep_X,dep_Y,n): which returns - selectk_features
#Here the number = 5 as Feature Selection which takes 5 Parameters as Input
k_Best = SelectKBest_Classification(indep_X,dep_Y,6)       

#Creating Empty Lists
accuracy_LogisticRegression = []
accuracy_SVM_Linear = []
accuracy_SVM_NonLinear = []
accuracy_KNN = []
accuracy_NaiveBayes = []
accuracy_DecisionTree = []
accuracy_RandomForest = []

k_Best

Selecting top 6 features using Chi-Square test

array([[3.00000000e+00, 1.48112676e+02, 5.74821053e+01, 3.07735602e+00,
        3.88689024e+01, 8.40819113e+03],
       [2.00000000e+00, 1.48112676e+02, 2.20000000e+01, 7.00000000e-01,
        3.40000000e+01, 1.23000000e+04],
       [1.00000000e+00, 9.90000000e+01, 2.30000000e+01, 6.00000000e-01,
        3.40000000e+01, 8.40819113e+03],
       ...,
       [3.00000000e+00, 1.10000000e+02, 1.15000000e+02, 6.00000000e+00,
        2.60000000e+01, 9.20000000e+03],
       [0.00000000e+00, 2.07000000e+02, 8.00000000e+01, 6.80000000e+00,
        3.88689024e+01, 8.40819113e+03],
       [0.00000000e+00, 1.00000000e+02, 4.90000000e+01, 1.00000000e+00,
        5.30000000e+01, 8.50000000e+03]])

In [25]:
#6.Calling a Created Function - train_test_split_and_StandardScaler: which returns - X_train, X_test, Y_train, Y_test
#Here before creating a Model, We are Selecting Few Best Columns as Input 
#Hence, Passing (k_Best, dep_Y) along with Selected Number of Features instead of Usual (indep_X, dep_Y)
X_train, X_test, Y_train, Y_test = train_test_split_and_StandardScaler(k_Best, dep_Y)   

#Creating Various Models as follows :

#7.Calling a Created Function - LogisticRegression(X_train,Y_train,X_test): which returns - classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score
classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score = LogisticRegression(X_train,Y_train,X_test)
accuracy_LogisticRegression.append(accuracy_score)

#8.Calling a Created Function - SVM_Linear(X_train,Y_train,X_test): which returns - classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score
classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score = SVM_Linear(X_train,Y_train,X_test)  
accuracy_SVM_Linear.append(accuracy_score)

#9.Calling a Created Function - SVM_Non_Linear(X_train,Y_train,X_test): which returns - classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score
classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score = SVM_Non_Linear(X_train,Y_train,X_test)  
accuracy_SVM_NonLinear.append(accuracy_score)

#10.Calling a Created Function - KNN(X_train,Y_train,X_test): which returns - classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score
classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score = KNN(X_train,Y_train,X_test)  
accuracy_KNN.append(accuracy_score)

#11.Calling a Created Function - Naive_Bayes(X_train,Y_train,X_test): which returns - classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score
classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score = Naive_Bayes(X_train,Y_train,X_test)  
accuracy_NaiveBayes.append(accuracy_score)

#12.Calling a Created Function - DecisionTree(X_train,Y_train,X_test): which returns - classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score
classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score = DecisionTree(X_train,Y_train,X_test)  
accuracy_DecisionTree.append(accuracy_score)

#13.Calling a Created Function - RandomForest(X_train,Y_train,X_test): which returns - classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score
classifier, X_test, Y_test, confusion_matrix, classification_report, accuracy_score = RandomForest(X_train,Y_train,X_test)  
accuracy_RandomForest.append(accuracy_score)
    
#14.Calling a Created Function - SelectK(With Below Parameters): which returns - dataframe    
result = SelectK_Classification(accuracy_LogisticRegression, accuracy_SVM_Linear, accuracy_SVM_NonLinear, 
                           accuracy_KNN, accuracy_NaiveBayes, accuracy_DecisionTree, accuracy_RandomForest)

C:\Anaconda\envs\AI_ML\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Anaconda\envs\AI_ML\lib\site-packages\sklearn\neighbors\base.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  old_joblib = LooseVersion(joblib_version) < LooseVersion('0.12')
C:\Anaconda\envs\AI_ML\lib\site-packages\sklearn\neighbors\base.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  old_joblib = LooseVersion(joblib_version) < LooseVersion('0.12')
C:\Anaconda\envs\AI_ML\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):
C:\Anaconda\envs\AI_ML\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):

In [26]:
# Calling the Final Results by Selecting Top 6 Features
result

,Logistic Regression,SVM Linear,SVM Non Linear,KNN,Naive Bayes,Decision Tree,Random Forest
ChiSquare,0.96,0.96,0.96,0.93,0.89,0.97,0.97

In [8]:
# Calling the Final Results by Selecting Top 5 Features
result

,Logistic Regression,SVM Linear,SVM Non Linear,KNN,Naive Bayes,Decision Tree,Random Forest
ChiSquare,0.94,0.94,0.95,0.89,0.83,0.96,0.95

In [14]:
# Calling the Final Results by Selecting Top 4 Features
result

,Logistic Regression,SVM Linear,SVM Non Linear,KNN,Naive Bayes,Decision Tree,Random Forest
ChiSquare,0.85,0.82,0.83,0.86,0.79,0.89,0.89

In [17]:
# Calling the Final Results by Selecting Top 3 Features
result

,Logistic Regression,SVM Linear,SVM Non Linear,KNN,Naive Bayes,Decision Tree,Random Forest
ChiSquare,0.82,0.82,0.82,0.85,0.8,0.84,0.83

In [20]:
# Calling the Final Results by Selecting Top 2 Features
result

,Logistic Regression,SVM Linear,SVM Non Linear,KNN,Naive Bayes,Decision Tree,Random Forest
ChiSquare,0.75,0.69,0.73,0.77,0.74,0.72,0.71

In [23]:
# Calling the Final Results by Selecting Top 1 Feature
result

,Logistic Regression,SVM Linear,SVM Non Linear,KNN,Naive Bayes,Decision Tree,Random Forest
ChiSquare,0.64,0.64,0.65,0.64,0.64,0.62,0.67